version: '3.8'

services:
  db:
    # mysql: https://hub.docker.com/_/mysql
    # - v5.7은 AWS Aurora Serverless 호환 버전
    image: mysql:5.7 
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    # 필요에 맞게 변경
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234 

volumes:
  db-data: